### ISSUE TITLE
"No matches" - undetected zLib streams

### ISSUE THREAD

**Issue by birdie-github** [schnaader/precomp-cpp#21] opened 2016-02-06 11:38 UTC
```
./precomp.exe -v -cn 2box4.zip

Precomp v0.4.3 - ALPHA version - USE FOR TESTING ONLY
Free for non-commercial use - Copyright 2006-2012 by Christian Schneider

Input file: 2box4.zip
Output file: 2box4.pcf

Using packjpg25.dll for JPG recompression.
--> packJPG library v2.5a (12/12/2011) by Matthias Stirner / Se <--
More about PackJPG here: http://www.elektronik.htw-aalen.de/packjpg

ZIP header detected
(0.00%) ZIP header detected at position 0
compressed size: 50222
uncompressed size: 108368
file name length: 9
extra field length: 0
(0.08%) Possible zLib-Stream in ZIP found at position 0, windowbits = 15
Can be decompressed to 108368 bytes
No matches
New size: 50364 instead of 50338

Done.
Time: 362 millisecond(s)

Recompressed streams: 0/1
ZIP streams: 0/1

None of the given compression and memory levels could be used.
There will be no gain compressing the output file.

```

> Can be decompressed to 108368 bytes
> No matches

That's obviously wrong. Can be and will not be. :-)

If this issue has already been resolved then I'm sorry.

[2box4.zip](https://github.com/schnaader/precomp-cpp/files/120264/2box4.zip)

**Comment by schnaader** [comment] 2016-02-06 15:31
This is a known bug. There is only one way to decompress a zLib stream, but many ways to compress it. At the moment, Precomp only tries the original 81 compression and memory level combinations from zLib - none of them gives the same compressed stream here - that's why it states "Can be decompressed" - but "No matches" (for recompression).

I'm currently working on a solution for this, essentially detecting, decompressing and recompressing zLib streams myself without zLib. There's a closed source solution for this [called reflate](http://encode.ru/threads/1399-reflate-a-new-universal-deflate-recompressor), I'll soon upload my own attempt (called "difflate") here on GitHub.

**Comment by birdie-github** [comment] 2016-02-06 15:56
I just wonder why you've closed this ticket: others will surely stumble upon this bug and file a new bug report.

**Comment by schnaader** [comment] 2016-02-07 00:49
You're right, closing the issue is wrong, editing the title is better.

Some versions earlier, the verbose output was much more verbose, listing every windowbits/level combination, so it seems there is some information lost now that could indeed be recovered changing the verbose output.

**Comment by schnaader** [comment] 2018-09-15 09:50
Fixed with preflate support (in current develop branch, will be 0.4.7). Results:

`-cn: 109.915 bytes`  (1/1 ZIP, completely decompressed)
`-cl: 38.693 bytes`

**Closed by schnaader** 2018-09-15 09:50 UTC
Labels: bug, deflate, enhancement, much work
