### ISSUE TITLE
random crashes with zlib compressed files

### ISSUE THREAD

**Issue by Godangel** [schnaader/precomp-cpp#128] opened 2021-05-22 01:39 UTC
Precomp randomly crashes while processing some zlib compressed files (inno setup files with zlib compression to be exact) with same errorlevel code -1073741819. Crashes are data independent. The same small file can be successfully processed 50 times, but crash at 51st. As for large files (like 20+ Gb) crashes occur almost every attempt. Tested both x64 and x86 versions. Also no issues with free space or RAM. Tested with antivirus disabled.
precomp.exe -cn -intense -t-pzgnfjsmb3 file.zip - random crashes
precomp.exe -cn -intense file.zip - random crashes
precomp.exe -cn file.zip - works fine, but no desired effect (obviously)

On the other hand, everything works fine after switching to previous precomp 0.46. Tested multiple times with different data files.

While testing on small files seems like the probability of crash significantly lowers after one or few passes on specific file (does somehow disk caching helps to prevent crashes..? dunno...). On large files somewhat similar behavior was observed a few times as after crash next run seemingly passes the point, where crash occur, but crashes somewhere afterwards.

Small data file (cutout part of larger archive) with tester script here:
https://www101.zippyshare.com/v/FBTEIhUc/file.html
Logs here: [logs.zip](https://github.com/schnaader/precomp-cpp/files/6525361/logs.zip)

As crashes occur more "reliably" on large files it's easier to use for testing genuinely big archives of software/games distribution or just copy the provided file multiple times and pack them in large (20+ Gb) zip without compression.

**Comment by schnaader** [comment] 2021-05-30 10:16
Thanks for the report and the test script. Unfortunately, I couldn't reproduce the problem yet.

Test machine: AMD Ryzen 5 4600H, 6 cores, 3 GHz, 4 GHz boost, 16 GB RAM, Windows 10 Pro 64-Bit.
Tried the script on the 500 MB file multiple times (last session did call precomp 390 times) without any crash.
After that, I created a big 8 MB file that contains the file 16 times. The adjusted script called precomp 5 times on the file but also didn't crash.

Since 0.4.6 works for you and 0.4.7 doesn't, my suspect is something multithreading-related in preflate, e.g. some race condition. Those are hard to reproduce/debug and since I could not reproduce the problem on my machine, I can only have a look at the code and look for anything suspicious.

I'll leave the issue opened, perhaps you or someone else can find ways to better reproduce this problem, perhaps it's related to a certain hardware configuration (what are your specs?). Last, but not least, I'll have a look at the code and also run the script on other big files containing zlib streams.

**Comment by Godangel** [comment] 2021-05-30 15:11
My config: Intel i9 9900K (8 cores, 16 threads, 4.7 GHz all core boost), 32 Gb RAM, Windows 10 Pro x64.

While trying to debug the issue and recompiled provided source with mingw64 v7.3 found out that strangely enough crashes occur roughly ~20 times less frequently.
- mingw provided with Qt
- used flags CMAKE_BUILD_TYPE=Release CMAKE_EXE_LINKER_FLAGS=-static
- commented out single line in liblzma\common\sysdefs.h as it caused compilation error
`//typedef unsigned char _Bool;`
[precomp.zip](https://github.com/schnaader/precomp-cpp/files/6566382/precomp.zip)

What compiler you used for 0.4.7? Still testing, but with mine it takes way too long to debug. I'll also try to test on another config.

**Comment by schnaader** [comment] 2021-05-30 21:20
The 0.4.7 binary was compiled using cmake and MSVC (Visual Studio 2017).

**Comment by Godangel** [comment] 2021-06-05 13:58
Update. After thorough testing can confirm that recompiled precomp 0.4.7 (provided in post above) produces zero random crashes. At first was confused by few rare errors, but then found out that they are not random, but rather data specific ones. So can safely assume random crashes are not directly code related, but some compiler optimizations related (and probably platform dependent). Though I didn't manage to thoroughly test it on another computers yet.

While it's likely unnecessary at this point, I include collected statistics. Tests were run on data sample, provided in the first post. In short: crashes very often during compression (every ~0.2-20 Gb tested), very rare during decompression (every 250++ Gb tested).
[testing.zip](https://github.com/schnaader/precomp-cpp/files/6602630/testing.zip)

**Comment by schnaader** [comment] 2021-06-05 14:04
Thanks for the research! Closing the issued, but I will keep an eye on that, it should be possible to build a stress test for future releases using different compilers and machines.

**Closed by schnaader** 2021-06-05 14:04 UTC
Labels: bug, deflate, preflate
